version: "3.7"
services:
  web:
    build: . #todo does this result in a new build?
    ports:
      - "8081:8080"
    depends_on:
      - mongo  #note the name is 'mongo' that we use to create the container
  mongo:  #this name is what the web service uses in the depends_on
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
volumes:
  mongo-volume: #created via docker cli in host