context:
  initializer:
    classes:  com.dood.tdd.kotlinmicroservice.users.config.Beans

#https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-mongodb
# v3 and newer mongo can only set the URI.  note no user/password
spring:
  data:
    mongodb:
#      uri: mongodb://mongodb/reactiveKotlinExperiment //this works with docker
      uri: mongodb://localhost/reactiveKotlinExperiment

#Actuator 2.x
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      apache: DEBUG